# Lab 3: Pytorch Fundamentals

### What is PyTorch?

PyTorch is an open source machine learning and deep learning framework.

In [4]:
!python --version

Python 3.14.2


In [5]:
# importing pytorch

import torch
torch.__version__

'2.12.0+cpu'

# Tensor
It is a multidimensional array used to store and process data. Everything including input data, model parameters, predictions and gradients in pytorch is represented as tensors. Basically, PyTorch performas all computations using tensors.


## Scalar
It is a single numerical value. It consists of magintude only and no dimensions.

In [6]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

torch.sensor(7) creates a tensor containing 7 values in which each of those values have no dimensions

In [7]:
print(scalar.ndim) # ndim= no of dimensions
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


ndim gives 0 as scalar has no dimensions

item converts one element tenmsor into a standard python number so tensor(7) becomes 7

shape is for dimensions of tensor and scalar has no dimension so empty

## Vector
It is a 1D tensor which containes multiple values arranged in a single row(list).

In [8]:
# vector
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

creates 1D tensor with 4 elements

In [9]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


ndim gives 1 as it is 1D

tensor has 4 elements

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside `([)` and you only need to count one side.

### 3.1.3. Matrix

It is 2D tensor consisting of rows and columns

In [10]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

3*3 matrix with 3 rows and 3 columns

In [11]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


ndim is 2 since it is 2D

shape gives 3*3 as it is a 3*3 matrix(3 rows and 3 columns)

## Tensor

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


ndim is 3 as it is 3D(can also be figured out by number of [ at the very start)

[1,3,3]

It can described as 1 matrix with 3 rows and 3 columns

The above `tensor`, can be the for example the following datasets: 

| Day of the week | Chiya Sales | Coffee Sales |
| :--- | :---: | ---: |
|  1 | 3 | 2 |
| 2 | 6 | 4 |
| 3 | 9 | 5 |

Or in Transposed form, we can write: 

| Day of the week | 1 | 2 |  3 |
| :--- | :---: | :---: | :---: |
| **Chiya Sales** | 3 | 6 | 9 |
| **Coffee Sales** | 2 | 4 | 5 |

## 3.1.4.1 Random Tensors

The values of random tensors are generated randomly

In [14]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.6425, 0.2924, 0.0017],
         [0.0664, 0.9750, 0.8016]]),
 torch.float32)

random_tensor = torch.rand(size=(2, 3))

creates a tensor with 2 rows and 3 columns and consists of random values between 0 and 1



random_tensor, random_tensor.dtype

torch.rand generates floating point numbers by default

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

([224, 224, 3]), 3)

([R, G, B],ndim)

## Tensors of only Zeros and Ones 

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

####  Creating a range and tensors like

In [18]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`torch.range()` is depreciated, therefore use `torch.arange()`

In [19]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor datatypes

datatype determines what kind of values can be stored, how much memory is used and precision of calculations

default datatype for tensors is float32


In [20]:
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

shape:what shape is the tensor

dtype:what datatype are the elements within the tensor stored in?

device:what device is the tensor stored on? 


In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7567, 0.9425, 0.8523, 0.8580],
        [0.3518, 0.3710, 0.6588, 0.6322],
        [0.9957, 0.3374, 0.3026, 0.9541]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations


- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication


In [23]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
tensor

tensor([1, 2, 3])

The operation `tensor * 10` creates a new tensor with the multiplied values, but it does not change the original `tensor`.

In [26]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [27]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [28]:
tensor

tensor([-9, -8, -7])

In [29]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


In [30]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


[1, 2, 3] · [1, 2, 3] 

= (1×1) + (2×2) + (3×3) 

= 1 + 4 + 9 

= 14

**One of the most common errors in deep learning (shape errors)**

In [34]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [35]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


**Finding the min, max, mean, sum, etc (aggregation)**

In [36]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


**Positional min/max**


In [37]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Change tensor datatype**

In [38]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

**Reshaping**



In [39]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [40]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

**View**



In [41]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [42]:
z = x.view(2,4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [43]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [44]:
import torch
x = torch.arange(6)
# print(x,x.shape)

a = x.view(2, 3)
b = x.reshape(2, 3)

a[0, 0] = 100
print(x)

tensor([100,   1,   2,   3,   4,   5])


That's the exact reason both functions exist: `view()` is a strict **"reinterpret the existing memory"** operation, while `reshape()` is a flexible **"give me this shape, even if a copy is needed"** operation.

**Stack**

- `torch.stack(tensors, dim=0)`:	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

In [45]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) 
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [46]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])

**Squeeze and Unsqueeze funtions.**

In [47]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


**permute**



In [ ]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


## Indexing


In [48]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [49]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1])# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


## Pytorch Tensor to NumPy arrays and vice versa


In [50]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [51]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Tensors on GPU

In [52]:
!nvidia-smi

Wed Jun 10 21:43:52 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 592.01                 Driver Version: 592.01         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5060 ...  WDDM  |   00000000:02:00.0 Off |                  N/A |
| N/A   41C    P8              7W /   50W |      72MiB /   8151MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [53]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [54]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [55]:
# Count number of devices
torch.cuda.device_count()

0

In [56]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [57]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Discussion 

In this lab we were introduced to the basic ideas behind PyTorch tensors. This includes scalars, vectors, matrices, and higher dimensional tensors. Various operations on tensor like creation, manipulation, reshaping, indexing and datatype conversion were performed. The lab also presented random tensors, zero and one tensors, and device management for efficient computation. It also showed how tensors can be moved between CPU and GPU devices and the ability of PyTorch for efficient computation for machine learning and deep learning applications.


## Conclusion

Overall, the lab was successful in demonstrating the key aspects and concepts related to PyTorch tensors and tensor operations. It helped understand how PyTorch tensors can be utilized as data structures for representing data used in various machine learning and deep learning tasks. By performing the relevant operations, important concepts including tensor creation, manipulation of tensors, performing mathematical operations on matrices, handling data types, tensor reshaping, indexing, and tensor placement on devices were learned. 